services:
  search_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  dashboard_kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - search_elasticsearch

  dashboard_grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "3000:3000"

  logshipper_webapi-filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.26
    container_name: logshipper_webapi
    volumes:
      - ./asimov-webapi/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./asimov-webapi/logs:/logs
    depends_on:
      - search_elasticsearch
