services:
  api-gateway_apache-apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    # restart: always
    volumes:
      - ./api-gateway/config/config.standalone.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    environment:
      - APISIX_STAND_ALONE=true
    ports:
      - "9180:9180" # Admin API
      - "9080:9080" # HTTP Proxy
      - "9443:9443" # HTTPS Proxy

  rdb_mysql:
    image: mysql:8.0  # MySQL 官方映像支援 ARM
    environment:
      MYSQL_DATABASE: asimov
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    volumes:
      - ./.docker-data/rdb_mysql:/var/lib/mysql
      # - ./init-scripts/init.ddl.sql:/docker-entrypoint-initdb.d/init.ddl.sql  # 加入初始化 SQL 檔案

  rdb-adminer_phpmyadmin:
    image: phpmyadmin  # PhpMyAdmin 支援 ARM
    ports:
      - 9999:80
    links:
      - rdb_mysql:db
    depends_on:
      rdb_mysql:
        condition: service_healthy

  cache_redis:
    image: redis:7.2-alpine  # Redis 官方映像支援 ARM
    ports:
      - 6379:6379
    volumes:
      - ./.docker-data/cache_redis/.docker-data:/.docker-data
      - ./.docker-data/cache_redis/conf/redis.conf:/usr/local/etc/redis/redis.conf

  cache-adminer_phpRedisAdmin:
    image: erikdubbelboer/phpredisadmin:1.19  # 這個映像應該也能運行在 ARM 上
    ports:
      - 9998:80
    environment:
      REDIS_1_HOST: cache_redis
      REDIS_1_NAME: localhost

  queue_rabbitmq:
    image: rabbitmq:3.12-management-alpine  # RabbitMQ 官方映像支援 ARM
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker-data/queue_rabbitmq/.docker-data:/var/lib/rabbitmq
      - ./.docker-data/queue_rabbitmq/log:/var/log/rabbitmq
      # - ./queue/init.sh:/docker-entrypoint-init.d/init_rabbitmq.sh
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    # command: bash /docker-entrypoint-init.d/init_rabbitmq.sh