version: "3.2"
services:
  api-gateway_apache-apisix:
    image: apache/apisix:3.11  # 使用 Apache APISIX 作為 API Gateway
    ports:
      - 9080:9080  # HTTP 端口
      - 9443:9443  # HTTPS 端口
    volumes:
      - ./api-gateway/config/config.standalone.yaml:/usr/local/apisix/conf/config.yaml  # 加入 APISIX 的配置檔案
    depends_on:
      rdb_mysql:
        condition: service_healthy
      queue_rabbitmq:
        condition: service_healthy


  rdb_mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: asimov
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    volumes:
      - ./.docker-data/rdb_mysql:/var/lib/mysql
      - ./init-scripts/init.ddl.sql:/docker-entrypoint-initdb.d/init.ddl.sql  # 加入初始化 SQL 檔案
    # networks:
    #   - service-network

  rdb-adminer_phpmyadmin:
    image: phpmyadmin
    ports:
      - 9999:80
    links:
      - rdb_mysql:db
    # networks:
    #   - service-network
    depends_on:
      rdb_mysql:
        condition: service_healthy

  cache_redis:
    image: redis:7.2-alpine
    ports:
        - 6379:6379
    volumes:
        - ./.docker-data/cache_redis/.docker-data:/.docker-data
        - ./.docker-data/cache_redis/conf/redis.conf:/usr/local/etc/redis/redis.conf

  cache-adminer_phpRedisAdmin:
    image: erikdubbelboer/phpredisadmin:1.19
    ports:
        - 9998:80
    environment:
      REDIS_1_HOST: cache_redis
      REDIS_1_NAME: localhost

  queue_rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.docker-data/queue_rabbitmq/.docker-data:/var/lib/rabbitmq
        - ./.docker-data/queue_rabbitmq/log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password

