apisix:
  node_listen: 9080             # HTTP proxy port
  enable_https: false           # Disable HTTPS
  stream_proxy:                 # Disable TCP/UDP proxy
    tcp: []
    udp: []
  admin_listen:
    ip: 0.0.0.0
    port: 9180                  # Admin API port

deployment:
  admin:
    admin_api_mtls: false       # Disable admin API mutual TLS
  role: data_plane              # Traditional mode for Standalone
  etcd:
    disable: true               # Disable etcd

routes:
  - uri: /version               # Define a route for `/version`
    name: version-route
    methods:
      - GET
    upstream:
      type: roundrobin
      nodes:
        "host.docker.internal:8080": 1
