@HOST=http://192.168.64.18:2375


### 
POST {{HOST}}/containers/create
Content-Type: application/json

{
    "Image": "hello-world",
    "HostConfig": {
        "AutoRemove": true
    }
}


### pull image
POST {{HOST}}/images/create?fromImage=hello-world



### start container
POST {{HOST}}/containers/{{container_id}}}/start



### 建立 Volume
POST {{HOST}}/volumes/create HTTP/1.1
Content-Type: application/json

{
  "Name": "my-volume",
  "Driver": "local"
}

> {% 
// 將回應中的 volume 名稱儲存到變數 volumeName
save("volumeName", json($.Name));
%}


### 建立 Container，並掛載剛剛建立的 Volume
POST {{HOST}}/containers/create HTTP/1.1
Content-Type: application/json

{
  "Image": "busybox",
  "Cmd": ["sh", "-c", "echo 'Hello Volume' > /data/hello.txt && sleep 10"],
  "HostConfig": {
    "Binds": [
      "{{volumeName}}:/data"
    ]
  }
}

> {% 
// 將回應中的 container ID 儲存到變數 containerId
save("containerId", json($.Id));
%}


### 啟動 Container
POST {{HOST}}/containers/{{containerId}}/start HTTP/1.1
