# -----------------------------------------------------------------------------
# Server (Tomcat)
# -----------------------------------------------------------------------------
## Product Metadata
server:
  port: ${port:8081}

  # Disable Whitelabel Error Page
  # see: https://websparrow.org/spring/how-to-resolve-whitelabel-error-page-in-spring-boot
  error:
    whitelabel:
      enabled: false


# -----------------------------------------------------------------------------
# Sprinboot
# -----------------------------------------------------------------------------
#spring.main.banner-mode=off
spring:
#  main:
#    banner-mode: off # see: https://stackoverflow.com/questions/26585959/how-to-disable-spring-boot-logo-in-stdout

  application:
    name: SaaS Consumer Server

  # datasource:
  #   url: jdbc:mysql://localhost:3306/asimov?allowPublicKeyRetrieval=true&useSSL=false
  #   username: root
  #   password: password

  # jpa:
  #   hibernate:
  #     dialect: org.hibernate.dialect.MySQLDialect

  #     # https://stackoverflow.com/questions/51136693/how-to-check-hikaricp-connection-pooling-is-working-or-not-in-java
  #     # lsof -nP -i :3306 -sTCP:ESTABLISHED
  #     # ss -46 -np state established dport = :3306 | grep 'java' | sort -r -k 3,3 | nl
  #     # netstat -ant | grep 3306
  #     # hikari:
  #     #   maximumPoolSize: 5
  #     #   minimumIdle: 5
  #     ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password

  # data:
  #   redis:
  #     database: 0
  #     host: localhost
  #     port: 6379
  #     # password: password
  #     # timeout: 60000


# -----------------------------------------------------------------------------
# logback
# -----------------------------------------------------------------------------
logging:
  path: ./logs
  level.com.gtcafe.asimov.apiserver: INFO


# -----------------------------------------------------------------------------
# Application
# -----------------------------------------------------------------------------

# app:
#   rabbitmq:
#     exchange: app.exchange1.topic1
#     queue: app.queue
#     routingkey: app.routingkey

app:
  rabbitmq:
    ## ATTENTTION: DON't CHANG the queueName, due to they are as the key in code
    queues:
    - name: sys.tasks
      exchange: directExchange
      routingKey: sys-task
    
    - name: platform.sayHello
      exchange: directExchange
      routingKey: platform-sayHello

    - name: platform.tenant
      exchange: directExchange
      routingKey: platform-tenant

    # - name: platform.tenant
    #   exchange: fanoutExchange
    #   routing-key: "" # Fanout exchange doesn't need routing key

# -----------------------------------------------------------------------------
# Security: JWT
# -----------------------------------------------------------------------------
# gtcafe.app.jwtCookieName=gtcafe
# gtcafe.app.jwtSecret= ======================Gtcafe=Spring===========================
# gtcafe.app.jwtExpirationMs=86400000
