@contentType = application/json
@hostname = http://localhost:8080/api


### apply a new tenant
POST {{hostname}}/tenants
content-type: {{contentType}}

{
  "tenantKey": "Tears-of-The-Kingdom",
  "displayName": "Tear of the Kingdom",
  "description": "王國之淚",
  "rootAccount": "rick@abc.com"
}


### get tenant status
GET {{hostname}}/tenants/Tears-of-The-Kingdom
content-type: {{contentType}}

### get by task
GET {{hostname}}/tasks/8f72bf5c-697a-4bc3-975e-64a75f854a77
content-type: {{contentType}}

