filebeat.inputs:
  - type: log
    paths:
      - /logs/*.log
    fields:
      app_name: api-app
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /home/ubuntu/asimov/api-server/logs/current.log
    fields:
      app_name: asimov.api-server
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    index: "asimov.api-server"  # 自定義索引標記

output.elasticsearch:
  # hosts: ["search_elasticsearch:9200"]
  hosts: ["host.docker.internal:9200"]
  protocol: "http"
setup.kibana:
  # host: "kibana:5601"
  host: "host.docker.internal:5601"
