@contentType = application/json
@hostname = http://localhost:8080/api/v1alpha/hello
# @hostname = http://192.168.64.18:9080


### ---
GET {{hostname}}

### -----
GET {{hostname}}
X-Tenant-Id: t-123
X-AppName: asimov
X-RoleName: admin

### normal case#1: not work, due to content-type specified
POST {{hostname}}
content-type: {{contentType}}
X-Tenant-Id: t-123
X-AppName: asimov
X-RoleName: admin

{
  "message": "Hello, Asimov"
}
