# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'metric-export-basic'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

## gtlab
  # - job_name: 'metric-export-basic'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['192.168.5.124:8080']

  - job_name: 'node-exporter_gtapp'
    static_configs:
      - targets: [
          '192.168.5.124:9100','192.168.5.120:9100','192.168.5.69:9100','192.168.5.235:9100',
          '192.168.5.36:9100'
        ]
  - job_name: 'node-exporter_gtinfa'
    static_configs:
      - targets: [
          '192.168.5.245:9100','192.168.5.236:9100'
        ]