filebeat.inputs:
  - type: log
    paths:
      - /home/ubuntu/asimov/api-server/logs/http-access-log.json
    fields:
      fb_app-name: asimov.api-server
      fb_log-type: access-log           # 你可以用這個來標示 log 類型
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    # index: "asimov.api-server"  # 自定義索引標記

  - type: log
    paths:
      - /home/ubuntu/asimov/api-server/logs/infra.cache.redis.json
    fields:
      fb_app-name: asimov.api-server
      fb_log-type: cache-access-log           # 你可以用這個來標示 log 類型
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    # index: "asimov.api-server"  # 自定義索引標記

  - type: log
    paths:
      - /home/ubuntu/asimov/api-server/logs/queue-producer-access-log.json
    fields:
      fb_app-name: asimov.api-server
      fb_log-type: queue-access-log           # 你可以用這個來標示 log 類型
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

## consumer server
  - type: log
    paths:
      - /home/ubuntu/asimov/consumer-server/logs/queue-consumer-access-log.json
    fields:
      fb_app-name: asimov.consumer-server
      fb_log-type: queue-access-log           # 你可以用這個來標示 log 類型
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    # index: "asimov.api-server"  # 自定義索引標記

  - type: log
    paths:
      - /home/ubuntu/asimov/consumer-server/logs/infra.cache.redis.json
    fields:
      fb_app-name: asimov.consumer-server
      fb_log-type: cache-access-log           # 你可以用這個來標示 log 類型
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    # index: "asimov.api-server"  # 自定義索引標記


# ============================== Elasticsearch output ===========================

output.elasticsearch:
  hosts: ["elastic.asimov.lab.gtcafe.com:9200"]
  protocol: "http"
  # username: "elastic"
  # password: "your_elastic_password"

  indices:
    - index: "asimov.api-server.access-log-%{+yyyy.MM.dd}"
      when.equals:
        fb_log-type: "access-log"

    - index: "asimov.api-server.cache-access-log-%{+yyyy.MM.dd}"
      when.equals:
        fb_log-type: "cache-access-log"

    - index: "asimov.api-server.queue-access-log-%{+yyyy.MM.dd}"
      when.equals:
        fb_log-type: "queue-access-log"


# ============================ Setup Kibana (optional) ==========================

setup.kibana:
  host: "kibana.asimov.lab.gtcafe.com:5601"

# ============================ Logging ==========================================

logging.level: info