global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'metric-export-basic'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.5.124:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.5.124:9100','192.168.5.120:9100','192.168.5.69:9100']
