@HOST=http://192.168.64.18:2375


### 
POST {{HOST}}/containers/create
Content-Type: application/json

{
    "Image": "hello-world",
    "HostConfig": {
        "AutoRemove": true
    }
}


### pull image
POST {{HOST}}/images/create?fromImage=nginx:latest


### start container
POST {{HOST}}/containers/{{container_id}}}/start



### 建立 Volume
POST {{HOST}}/volumes/create
Content-Type: application/json

{
  "Name": "my-volume",
  "Driver": "local"
}

# > {% 
# // 將回應中的 volume 名稱儲存到變數 volumeName
# save("volumeName", json($.Name));
# %}

###
POST {{HOST}}/images/create?fromImage=busybox

### 建立 Container，並掛載剛剛建立的 Volume
POST {{HOST}}/containers/create
Content-Type: application/json

{
  "Image": "busybox:1",
  "Cmd": ["sh", "-c", "echo 'Hello Volume' > /data/hello.txt && sleep 10"],
  "HostConfig": {
    "Binds": [
      "my-volum:/data"
    ]
  }
}

# > {% 
# // 將回應中的 container ID 儲存到變數 containerId
# save("containerId", json($.Id));
# %}


### query container: list all
GET {{HOST}}/containers/json?all=true


### query container: limit count
GET {{HOST}}/containers/json?filters={"status":["running"]}



