@contentType = application/json
@hostname = http://localhost:8080


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/tasks/36dd7f9b-9494-4bb4-99a3-dbb58830cd31