@contentType = application/json
@hostname = http://localhost:8080


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/tasks/9728e822-d21b-4e53-8f76-04a6dafc8b3b