@contentType = application/json
# @hostname = http://localhost:8080
@hostname = https://rws.lab.gtcafe.com
#@hostname = https://lab.gtcafe.com


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/v1alpha/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/v1alpha/tasks/37f11041-5fba-4cd7-96d9-d2de3be61839


