@contentType = application/json
@hostname = http://localhost:8080
#@hostname = https://rws.lab.gtcafe.com
#@hostname = https://lab.gtcafe.com


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/v1alpha/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/v1alpha/tasks/c62ce699-ca1f-4bd0-87aa-3a63217a713e


