@contentType = application/json
# @hostname = http://localhost:8080
@hostname = https://rws.lab.gtcafe.com
#@hostname = https://lab.gtcafe.com


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/v1alpha/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/v1alpha/tasks/5f31c03d-e542-4f6c-abb8-6006a544eb67


