@contentType = application/json
@hostname = http://localhost:8080


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/tasks/28f6d7c7-1773-44f3-aad5-e8feff09371a