@contentType = application/json
@hostname = http://localhost:8080


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/tasks/b6c3cc26-4b4b-4849-9f48-e2b052fe5aa3