@contentType = application/json
@hostname = http://localhost:8080


# -----------------------------------------------------------------------------
### normal case#1:
POST {{hostname}}/api/hello
Content-Type: {{contentType}}
X-Request-Mode: async

{
  "message": "Hello, Asimov"
}


### get status
GET {{hostname}}/api/tasks/11a5c02c-b41a-4b71-8335-8cda1c9730ca