# -----------------------------------------------------------------------------
# Server (Tomcat)
# -----------------------------------------------------------------------------
server:
  port: ${port:8080}
  error:
    whitelabel:
      enabled: false
  address: 0.0.0.0

# -----------------------------------------------------------------------------
# Sprinboot
# -----------------------------------------------------------------------------
spring:
  #  main:
  #    banner-mode: off

  application:
    name: WebAPI Server

  datasource:
    # url: jdbc:mysql://localhost:3306/asimov?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mariadb://localhost:3306/asimov?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: medusa
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      # dialect: org.hibernate.dialect.MySQLDialect
      dialect: org.hibernate.dialect.MariaDBDialect

      # https://stackoverflow.com/questions/51136693/how-to-check-hikaricp-connection-pooling-is-working-or-not-in-java
      # lsof -nP -i :3306 -sTCP:ESTABLISHED
      # ss -46 -np state established dport = :3306 | grep 'java' | sort -r -k 3,3 | nl
      # netstat -ant | grep 3306
      # hikari:
      #   maximumPoolSize: 5
      #   minimumIdle: 5
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: medusa

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      # password: password
      # timeout: 60000

# -----------------------------------------------------------------------------
# logback
# -----------------------------------------------------------------------------
logging:
  # path: ./logs
  level:
    com.gtcafe.asimov: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true

  ## http://localhost:8080/swagger-ui/index.html
  swagger-ui:
    path: /swagger-ui.html
    # operationsSorter: name

# -----------------------------------------------------------------------------
# Application
# -----------------------------------------------------------------------------

app:
  openapi:
    version: v1
    title: Asimov
    description: Asimov API
  time:
    zone: UTC
    format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  rabbitmq:
    autoInit: true
    reset: true
    # prefixName: asimov

    ## ATTENTTION: DON't CHANGE the queueName, due to they are as the key in code
    ## TODO: move to core

    queues:
      - name: asimov.platform.task
        exchange: asimov.directExchange
        routingKey: platform-task

      - name: asimov.platform.hello
        exchange: asimov.directExchange
        routingKey: platform-hello

      - name: asimov.platform.tenant
        exchange: asimov.directExchange
        routingKey: platform-tenant

    # - name: platform.tenant
    #   exchange: fanoutExchange
    #   routing-key: "" # Fanout exchange doesn't need routing key

# -----------------------------------------------------------------------------
# Actuator Configuration
# -----------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        # include: health,metrics,prometheus
        include: metrics,prometheus

    # health:
    #   show-details: always

    metrics:
      tags:
        application: ${spring.application.name}

      # Custom Metrics Configuration
      # enable:
      #   all: true
      #   jvm: true
      # process: true
      #   system: true
      #   logback: true
      #   tomcat: true
