@contentType = application/json
@hostname = http://localhost:8080

## -----
### create a task: core.Hello::sayHello
GET {{hostname}}/api/hello
content-type: {{contentType}}

### case#2:
POST {{hostname}}/api/hello
content-type: {{contentType}}

{
  "message": "Hello, Asimov"
}

### abnormal case#2:
POST {{hostname}}/api/hello
content-type: {{contentType}}

{

}
