@contentType = application/json
@hostname = http://localhost:8080/api


### apply a new tenant
POST {{hostname}}/tenants
content-type: {{contentType}}

{
  "tenantKey": "Tears-of-The-Kingdom",
  "displayName": "Tear of the Kingdom",
  "description": "王國之淚",
  "rootAccount": "rick@abc.com"
}


### get tenant status
GET {{hostname}}/tenants/this-is-a-tenant-uniqu
content-type: {{contentType}}

### get by task
GET {{hostname}}/tasks/1e37839e-f81c-44e6-acbf-1efc8633acdf
content-type: {{contentType}}

