@contentType = application/json

@hostname = http://localhost:8080/api



### Send Message
GET {{hostname}}/



### Send Message
POST {{hostname}}/container
content-type: {{contentType}}

{
  "content": "rick"
}
