server:
  port: 8081

app:
  task:
    hostname: http://localhost:8080
    # hostname: https://rws.lab.gtcafe.com
    max-request: 30
    poll-interval-ms: 500
    thread-pool:
      core-size: 32
      max-size: 128
      queue-capacity: 1024
      thread-name-refix: client-
