spring:
  config:
    import: "optional:classpath:application-core.yml"
  main:
    banner-mode: off
  application:
    name: ApiServer

server:
  port: ${port:8080}
  error:
    whitelabel:
      enabled: false
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        name: rSessionId
        max-age: 3600

logging:
  level:
    org.springframework.boot.context.config: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
